// <auto-generated />
using DSS_Clothes.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSS_Clothes.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220519162412_DBClothes_2")]
    partial class DBClothes_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DSS_Clothes.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"), 1L, 1);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrandYear")
                        .HasColumnType("int");

                    b.HasKey("BrandID");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("DSS_Clothes.Models.Clothe", b =>
                {
                    b.Property<int>("ClotheID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClotheID"), 1L, 1);

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<string>("ClotheName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClotheID");

                    b.HasIndex("BrandID");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("DSS_Clothes.Models.Designer", b =>
                {
                    b.Property<int>("DesignerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignerID"), 1L, 1);

                    b.Property<int>("ClotheID")
                        .HasColumnType("int");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.HasKey("DesignerID");

                    b.HasIndex("ClotheID");

                    b.HasIndex("StoreID");

                    b.ToTable("Designers");
                });

            modelBuilder.Entity("DSS_Clothes.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"), 1L, 1);

                    b.Property<int>("ClotheID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("ClotheID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("DSS_Clothes.Models.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreID"), 1L, 1);

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoreID");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("DSS_Clothes.Models.Clothe", b =>
                {
                    b.HasOne("DSS_Clothes.Models.Brand", "Brand")
                        .WithMany("Clothes")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("DSS_Clothes.Models.Designer", b =>
                {
                    b.HasOne("DSS_Clothes.Models.Clothe", "Clothes")
                        .WithMany("Designers")
                        .HasForeignKey("ClotheID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DSS_Clothes.Models.Store", "Stores")
                        .WithMany("Designers")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothes");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("DSS_Clothes.Models.Image", b =>
                {
                    b.HasOne("DSS_Clothes.Models.Clothe", "Clothe")
                        .WithMany("Images")
                        .HasForeignKey("ClotheID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothe");
                });

            modelBuilder.Entity("DSS_Clothes.Models.Brand", b =>
                {
                    b.Navigation("Clothes");
                });

            modelBuilder.Entity("DSS_Clothes.Models.Clothe", b =>
                {
                    b.Navigation("Designers");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DSS_Clothes.Models.Store", b =>
                {
                    b.Navigation("Designers");
                });
#pragma warning restore 612, 618
        }
    }
}
